geometry:
  pinch_ratio_threshold: 0.15  # Относительный порог щипка (0.15 = 15% от размера ладони)
  threshold_index: 155
  threshold_middle: 145
  threshold_ring: 145
  threshold_pinky: 140
  threshold_thumb: 0.12
  
filter:
  min_cutoff: 0.3     # меньше = сильнее сглаживание на низких скоростях
  beta: 0.005      # скорость реакции на резкие движения
  derivate_cutoff: 1.0

vision:
  min_detection_confidence: 0.7
  min_tracking_confidence: 0.5
  max_num_hands: 2

camera:
  width: 640
  height: 480
  fps_target: 30
  device_id: 0
  mirror: True

mouse:
  sensitivity: 35.0       # Базовая чувствительность (чем выше, тем медленнее)
  acceleration: 0.15         # Сила ускорения при резких движениях (для быстрых разворотов)
  dead_zone: 15.0             # Мертвая зона (подавляет микродрожание руки)
  max_move_per_frame: 80    # Максимальный рывок мыши за 1 кадр (защита от телепортации курсора)
  click_debounce: 0.12       # Минимальное время (сек) между кликом и отпусканием (спасает выделение)

